export const CODE_TYPES = {
  MATMSG: 'MATMSG',
  MAILTO: 'MAILTO',
  SMS: 'SMSTO',
  WIFI: 'WIFI',
  TEL: 'TEL',
  VINFO: 'BEGIN',
  EVENT: 'VEVENT',
  ALARM: 'VALARM',
  CARD: 'VCARD',
  GEO: 'GEO',
  GEOM: 'GEOM',
  GEOM2: 'GEOM2',
  TEXT: 'TEXT',
  URL: 'URL',
};
